# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_complexrestorationproject import ComplexRestorationProject
from ..types.classes.cls_manuscriptcondition import ManuscriptCondition
from ..types.classes.cls_manuscriptcontext import ManuscriptContext
from ..types.classes.cls_restoration import Restoration
from ..types.enums.enm_manuscriptstate import ManuscriptState
from ..types.enums.enm_materialorigin import MaterialOrigin
from ..types.enums.enm_timeperiod import TimePeriod
from ..types.partial.classes.cls_complexrestorationproject import PartialComplexRestorationProject
from ..types.partial.classes.cls_manuscriptcondition import PartialManuscriptCondition
from ..types.partial.classes.cls_manuscriptcontext import PartialManuscriptContext
from ..types.partial.classes.cls_restoration import PartialRestoration
from baml_core.stream import AsyncStream
from typing import Callable, Protocol, runtime_checkable


import typing

import pytest
from contextlib import contextmanager
from unittest import mock

ImplName = typing.Literal["v1"]

T = typing.TypeVar("T", bound=typing.Callable[..., typing.Any])
CLS = typing.TypeVar("CLS", bound=type)


IAnalyzeRestorationProjectOutput = ComplexRestorationProject

@runtime_checkable
class IAnalyzeRestorationProject(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        ComplexRestorationProject
    """

    async def __call__(self, arg: str, /) -> ComplexRestorationProject:
        ...

   

@runtime_checkable
class IAnalyzeRestorationProjectStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        arg: str

    Returns:
        AsyncStream[ComplexRestorationProject, PartialComplexRestorationProject]
    """

    def __call__(self, arg: str, /) -> AsyncStream[ComplexRestorationProject, PartialComplexRestorationProject]:
        ...
class BAMLAnalyzeRestorationProjectImpl:
    async def run(self, arg: str, /) -> ComplexRestorationProject:
        ...
    
    def stream(self, arg: str, /) -> AsyncStream[ComplexRestorationProject, PartialComplexRestorationProject]:
        ...

class IBAMLAnalyzeRestorationProject:
    def register_impl(
        self, name: ImplName
    ) -> typing.Callable[[IAnalyzeRestorationProject, IAnalyzeRestorationProjectStream], None]:
        ...

    async def __call__(self, arg: str, /) -> ComplexRestorationProject:
        ...

    def stream(self, arg: str, /) -> AsyncStream[ComplexRestorationProject, PartialComplexRestorationProject]:
        ...

    def get_impl(self, name: ImplName) -> BAMLAnalyzeRestorationProjectImpl:
        ...

    @contextmanager
    def mock(self) -> typing.Generator[mock.AsyncMock, None, None]:
        """
        Utility for mocking the AnalyzeRestorationProjectInterface.

        Usage:
            ```python
            # All implementations are mocked.

            async def test_logic() -> None:
                with baml.AnalyzeRestorationProject.mock() as mocked:
                    mocked.return_value = ...
                    result = await AnalyzeRestorationProjectImpl(...)
                    assert mocked.called
            ```
        """
        ...

    @typing.overload
    def test(self, test_function: T) -> T:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the AnalyzeRestorationProjectInterface.

        Args:
            test_function : T
                The test function to be decorated.

        Usage:
            ```python
            # All implementations will be tested.

            @baml.AnalyzeRestorationProject.test
            async def test_logic(AnalyzeRestorationProjectImpl: IAnalyzeRestorationProject) -> None:
                result = await AnalyzeRestorationProjectImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, *, exclude_impl: typing.Iterable[ImplName] = [], stream: bool = False) -> pytest.MarkDecorator:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the AnalyzeRestorationProjectInterface.

        Args:
            exclude_impl : Iterable[ImplName]
                The names of the implementations to exclude from testing.
            stream: bool
                If set, will return a streamable version of the test function.

        Usage:
            ```python
            # All implementations except the given impl will be tested.

            @baml.AnalyzeRestorationProject.test(exclude_impl=["implname"])
            async def test_logic(AnalyzeRestorationProjectImpl: IAnalyzeRestorationProject) -> None:
                result = await AnalyzeRestorationProjectImpl(...)
            ```

            ```python
            # Streamable version of the test function.

            @baml.AnalyzeRestorationProject.test(stream=True)
            async def test_logic(AnalyzeRestorationProjectImpl: IAnalyzeRestorationProjectStream) -> None:
                async for result in AnalyzeRestorationProjectImpl(...):
                    ...
            ```
        """
        ...

    @typing.overload
    def test(self, test_class: typing.Type[CLS]) -> typing.Type[CLS]:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the AnalyzeRestorationProjectInterface.

        Args:
            test_class : Type[CLS]
                The test class to be decorated.

        Usage:
        ```python
        # All implementations will be tested in every test method.

        @baml.AnalyzeRestorationProject.test
        class TestClass:
            def test_a(self, AnalyzeRestorationProjectImpl: IAnalyzeRestorationProject) -> None:
                ...
            def test_b(self, AnalyzeRestorationProjectImpl: IAnalyzeRestorationProject) -> None:
                ...
        ```
        """
        ...

BAMLAnalyzeRestorationProject: IBAMLAnalyzeRestorationProject
