# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_address import Address
from ..types.classes.cls_item import Item
from ..types.classes.cls_orderinfo3 import OrderInfo3
from ..types.enums.enm_states import States
from ..types.partial.classes.cls_address import PartialAddress
from ..types.partial.classes.cls_item import PartialItem
from ..types.partial.classes.cls_orderinfo3 import PartialOrderInfo3
from baml_core.stream import AsyncStream
from baml_lib._impl.functions import BaseBAMLFunction
from typing import AsyncIterator, Callable, Protocol, runtime_checkable


IExtractOrderInfo3Output = OrderInfo3

@runtime_checkable
class IExtractOrderInfo3(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        OrderInfo3
    """

    async def __call__(self, arg: str, /) -> OrderInfo3:
        ...

   

@runtime_checkable
class IExtractOrderInfo3Stream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        arg: str

    Returns:
        AsyncStream[OrderInfo3, PartialOrderInfo3]
    """

    def __call__(self, arg: str, /) -> AsyncStream[OrderInfo3, PartialOrderInfo3]:
        ...
class IBAMLExtractOrderInfo3(BaseBAMLFunction[OrderInfo3, PartialOrderInfo3]):
    def __init__(self) -> None:
        super().__init__(
            "ExtractOrderInfo3",
            IExtractOrderInfo3,
            ["v1"],
        )

    async def __call__(self, *args, **kwargs) -> OrderInfo3:
        return await self.get_impl("v1").run(*args, **kwargs)
    
    def stream(self, *args, **kwargs) -> AsyncStream[OrderInfo3, PartialOrderInfo3]:
        res = self.get_impl("v1").stream(*args, **kwargs)
        return res

BAMLExtractOrderInfo3 = IBAMLExtractOrderInfo3()

__all__ = [ "BAMLExtractOrderInfo3" ]
