# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_orderinfo import OrderInfo
from ..types.partial.classes.cls_orderinfo import PartialOrderInfo
from baml_core.stream import AsyncStream
from typing import Callable, Protocol, runtime_checkable


import typing

import pytest
from contextlib import contextmanager
from unittest import mock

ImplName = typing.Literal["v1"]

T = typing.TypeVar("T", bound=typing.Callable[..., typing.Any])
CLS = typing.TypeVar("CLS", bound=type)


IExtractOrderInfoOutput = OrderInfo

@runtime_checkable
class IExtractOrderInfo(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        OrderInfo
    """

    async def __call__(self, arg: str, /) -> OrderInfo:
        ...

   

@runtime_checkable
class IExtractOrderInfoStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        arg: str

    Returns:
        AsyncStream[OrderInfo, PartialOrderInfo]
    """

    def __call__(self, arg: str, /) -> AsyncStream[OrderInfo, PartialOrderInfo]:
        ...
class BAMLExtractOrderInfoImpl:
    async def run(self, arg: str, /) -> OrderInfo:
        ...
    
    def stream(self, arg: str, /) -> AsyncStream[OrderInfo, PartialOrderInfo]:
        ...

class IBAMLExtractOrderInfo:
    def register_impl(
        self, name: ImplName
    ) -> typing.Callable[[IExtractOrderInfo, IExtractOrderInfoStream], None]:
        ...

    async def __call__(self, arg: str, /) -> OrderInfo:
        ...

    def stream(self, arg: str, /) -> AsyncStream[OrderInfo, PartialOrderInfo]:
        ...

    def get_impl(self, name: ImplName) -> BAMLExtractOrderInfoImpl:
        ...

    @contextmanager
    def mock(self) -> typing.Generator[mock.AsyncMock, None, None]:
        """
        Utility for mocking the ExtractOrderInfoInterface.

        Usage:
            ```python
            # All implementations are mocked.

            async def test_logic() -> None:
                with baml.ExtractOrderInfo.mock() as mocked:
                    mocked.return_value = ...
                    result = await ExtractOrderInfoImpl(...)
                    assert mocked.called
            ```
        """
        ...

    @typing.overload
    def test(self, test_function: T) -> T:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ExtractOrderInfoInterface.

        Args:
            test_function : T
                The test function to be decorated.

        Usage:
            ```python
            # All implementations will be tested.

            @baml.ExtractOrderInfo.test
            async def test_logic(ExtractOrderInfoImpl: IExtractOrderInfo) -> None:
                result = await ExtractOrderInfoImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, *, exclude_impl: typing.Iterable[ImplName] = [], stream: bool = False) -> pytest.MarkDecorator:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ExtractOrderInfoInterface.

        Args:
            exclude_impl : Iterable[ImplName]
                The names of the implementations to exclude from testing.
            stream: bool
                If set, will return a streamable version of the test function.

        Usage:
            ```python
            # All implementations except the given impl will be tested.

            @baml.ExtractOrderInfo.test(exclude_impl=["implname"])
            async def test_logic(ExtractOrderInfoImpl: IExtractOrderInfo) -> None:
                result = await ExtractOrderInfoImpl(...)
            ```

            ```python
            # Streamable version of the test function.

            @baml.ExtractOrderInfo.test(stream=True)
            async def test_logic(ExtractOrderInfoImpl: IExtractOrderInfoStream) -> None:
                async for result in ExtractOrderInfoImpl(...):
                    ...
            ```
        """
        ...

    @typing.overload
    def test(self, test_class: typing.Type[CLS]) -> typing.Type[CLS]:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ExtractOrderInfoInterface.

        Args:
            test_class : Type[CLS]
                The test class to be decorated.

        Usage:
        ```python
        # All implementations will be tested in every test method.

        @baml.ExtractOrderInfo.test
        class TestClass:
            def test_a(self, ExtractOrderInfoImpl: IExtractOrderInfo) -> None:
                ...
            def test_b(self, ExtractOrderInfoImpl: IExtractOrderInfo) -> None:
                ...
        ```
        """
        ...

BAMLExtractOrderInfo: IBAMLExtractOrderInfo
