# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_piidata import PIIData
from ..types.partial.classes.cls_piidata import PartialPIIData
from baml_core.stream import AsyncStream
from baml_lib._impl.functions import BaseBAMLFunction
from typing import AsyncIterator, Callable, List, Protocol, runtime_checkable


IExtractPIIOutput = List[PIIData]

@runtime_checkable
class IExtractPII(Protocol):
    """
    This is the interface for a function.

    Args:
        arg: str

    Returns:
        List[PIIData]
    """

    async def __call__(self, arg: str, /) -> List[PIIData]:
        ...

   

@runtime_checkable
class IExtractPIIStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        arg: str

    Returns:
        AsyncStream[List[PIIData], List[PIIData]]
    """

    def __call__(self, arg: str, /) -> AsyncStream[List[PIIData], List[PIIData]]:
        ...
class IBAMLExtractPII(BaseBAMLFunction[List[PIIData], List[PIIData]]):
    def __init__(self) -> None:
        super().__init__(
            "ExtractPII",
            IExtractPII,
            ["v1"],
        )

    async def __call__(self, *args, **kwargs) -> List[PIIData]:
        return await self.get_impl("v1").run(*args, **kwargs)
    
    def stream(self, *args, **kwargs) -> AsyncStream[List[PIIData], List[PIIData]]:
        res = self.get_impl("v1").stream(*args, **kwargs)
        return res

BAMLExtractPII = IBAMLExtractPII()

__all__ = [ "BAMLExtractPII" ]
